### ISSUE TITLE
New docker extension self-publish process

### ISSUE THREAD

**Issue by benja-M-1** [cto-ai/docker-extension-zsh#2]
Hi @kc-dot-io 👋 

I am Ben from the Docker Extensions team 😃 In case you didn't know, we released a new way to publish your extension on the marketplace last week: https://docs.docker.com/desktop/extensions-sdk/extensions/publish/. 

Would you be interested in submitting this extension?

**Comment by kc-dot-io** [comment]
@benja-M-1 Thanks for reaching out. @jossemargt-cto-ai and I were actually discussing this recently.

Yes, we'd be interested in submitting the extension. We'll take a look at this.

**Comment by kc-dot-io** [comment]
@benja-M-1: https://github.com/docker/extensions-submissions/issues/58

**Comment by benja-M-1** [comment]
Awesome 🤩 I believe we can close this issue 😀 Thanks for your quick reply!
